no_document use_thys [
            "../Collections/Collections",
            "../Refine/Refine",
            "../Refine/Collection_Bindings",
            "../Refine/Autoref_Collection_Bindings",
            "~~/src/HOL/Library/Efficient_Nat"
];


use_thys [
         "Introduction",
         "Dijkstra_Misc",
         "Graph",
         "Weight",
         "Dijkstra",
         "GraphSpec",
         "GraphGA",
         "GraphByMap",
         "HashGraphImpl",
         "Dijkstra_Impl",
         "Dijkstra_Impl_Adet",
         "Test"

];
