theory Hash_Declaration
imports Complex_Main

begin

type_synonym interfaces__unsigned_32' = " int "
type_synonym block_index' = " int "
type_synonym message_index' = " int "
record chain' = 
  h0'chain :: " int "
  h1'chain :: " int "
  h2'chain :: " int "
  h3'chain :: " int "
  h4'chain :: " int "
type_synonym block' = " int => int "
type_synonym message' = " int => block' "
consts block___default_arr'' :: " block' "
consts block___default_arr_element'' :: " int "
consts block_index__base__first'' :: " int "
consts block_index__base__last'' :: " int "
consts block_index__first'' :: " int "
consts block_index__last'' :: " int "
consts block_index__size'' :: " int "
consts ca'' :: " int "
consts ca__1'' :: " int "
consts ca__1___init'' :: " int "
consts ca__1___loopinit'' :: " int "
consts ca___init'' :: " int "
consts ca___loopinit'' :: " int "
consts ca_init'' :: " int "
consts cb'' :: " int "
consts cb__1'' :: " int "
consts cb__1___init'' :: " int "
consts cb__1___loopinit'' :: " int "
consts cb___init'' :: " int "
consts cb___loopinit'' :: " int "
consts cb_init'' :: " int "
consts cc'' :: " int "
consts cc__1'' :: " int "
consts cc__1___init'' :: " int "
consts cc__1___loopinit'' :: " int "
consts cc___init'' :: " int "
consts cc___loopinit'' :: " int "
consts cc_init'' :: " int "
consts cd'' :: " int "
consts cd__1'' :: " int "
consts cd__1___init'' :: " int "
consts cd__1___loopinit'' :: " int "
consts cd___init'' :: " int "
consts cd___loopinit'' :: " int "
consts cd_init'' :: " int "
consts ce'' :: " int "
consts ce__1'' :: " int "
consts ce__1___init'' :: " int "
consts ce__1___loopinit'' :: " int "
consts ce___init'' :: " int "
consts ce___loopinit'' :: " int "
consts ce_init'' :: " int "
consts chain___default_rcd'' :: " chain' "
consts chain__size'' :: " int "
consts interfaces__unsigned_32__base__first'' :: " int "
consts interfaces__unsigned_32__base__last'' :: " int "
consts interfaces__unsigned_32__first'' :: " int "
consts interfaces__unsigned_32__last'' :: " int "
consts interfaces__unsigned_32__modulus'' :: " int "
consts interfaces__unsigned_32__size'' :: " int "
consts loop__1__i'' :: " int "
consts loop__1__i___init'' :: " int "
consts loop__1__i___loopinit'' :: " int "
consts message___default_arr'' :: " message' "
consts message___default_arr_element'' :: " block' "
consts message_index__base__first'' :: " int "
consts message_index__base__last'' :: " int "
consts message_index__first'' :: " int "
consts message_index__last'' :: " int "
consts message_index__size'' :: " int "
consts word__base__first'' :: " int "
consts word__base__last'' :: " int "
consts word__first'' :: " int "
consts word__last'' :: " int "
consts word__modulus'' :: " int "
consts word__size'' :: " int "
consts x'' :: " message' "
consts x___init'' :: " message' "
consts x___loopinit'' :: " message' "
consts x__index__subtype__1__base__first'' :: " int "
consts x__index__subtype__1__base__last'' :: " int "
consts x__index__subtype__1__first'' :: " int "
consts x__index__subtype__1__last'' :: " int "
consts bit__not' :: " [ int , int ] => int "
consts block___mk_const_arr' :: " int => block' "
consts character__pos' :: " int => int "
consts character__val' :: " int => int "
consts int___abs' :: " int => int "
consts int___div' :: " [ int , int ] => int "
consts int___exp' :: " [ int , int ] => int "
consts int___mod' :: " [ int , int ] => int "
consts int___odd' :: " int => bool "
consts int___rem' :: " [ int , int ] => int "
consts int___times' :: " [ int , int ] => int "
consts int___to_real' :: " int => real "
consts message___mk_const_arr' :: " block' => message' "
consts real___abs' :: " real => real "
consts real___div' :: " [ real , real ] => real "
consts real___exp' :: " [ real , int ] => real "
consts real___minus' :: " [ real , real ] => real "
consts real___plus' :: " [ real , real ] => real "
consts real___times' :: " [ real , real ] => real "
consts real___uminus' :: " real => real "
consts round__' :: " real => int "

end
