theory K_R_Spark_Declaration
imports Complex_Main

begin

type_synonym interfaces__unsigned_32' = " int "
type_synonym round_index' = " int "
consts interfaces__unsigned_32__base__first'' :: " int "
consts interfaces__unsigned_32__base__last'' :: " int "
consts interfaces__unsigned_32__first'' :: " int "
consts interfaces__unsigned_32__last'' :: " int "
consts interfaces__unsigned_32__modulus'' :: " int "
consts interfaces__unsigned_32__size'' :: " int "
consts j'' :: " int "
consts j___init'' :: " int "
consts j___loopinit'' :: " int "
consts round_index__base__first'' :: " int "
consts round_index__base__last'' :: " int "
consts round_index__first'' :: " int "
consts round_index__last'' :: " int "
consts round_index__size'' :: " int "
consts word__base__first'' :: " int "
consts word__base__last'' :: " int "
consts word__first'' :: " int "
consts word__last'' :: " int "
consts word__modulus'' :: " int "
consts word__size'' :: " int "
consts bit__not' :: " [ int , int ] => int "
consts character__pos' :: " int => int "
consts character__val' :: " int => int "
consts int___abs' :: " int => int "
consts int___div' :: " [ int , int ] => int "
consts int___exp' :: " [ int , int ] => int "
consts int___mod' :: " [ int , int ] => int "
consts int___odd' :: " int => bool "
consts int___rem' :: " [ int , int ] => int "
consts int___times' :: " [ int , int ] => int "
consts int___to_real' :: " int => real "
consts real___abs' :: " real => real "
consts real___div' :: " [ real , real ] => real "
consts real___exp' :: " [ real , int ] => real "
consts real___minus' :: " [ real , real ] => real "
consts real___plus' :: " [ real , real ] => real "
consts real___times' :: " [ real , real ] => real "
consts real___uminus' :: " real => real "
consts round__' :: " real => int "

end
