no_document use_thys
  ["F_Spark_Declaration",
    "K_L_Spark_Declaration",
    "K_R_Spark_Declaration",
    "R_L_Spark_Declaration",
    "R_R_Spark_Declaration",
    "S_L_Spark_Declaration",
    "S_R_Spark_Declaration",
    "Round_Declaration",
    "Hash_Declaration"];

use_thys
  ["RMD",
    "Global_Specification",
    "F_Spark_User",
    "K_L_Spark_User",
    "K_R_Spark_User",
    "Global_User",
    "R_L_Spark_User",
    "R_R_Spark_User",
    "S_L_Spark_User",
    "S_R_Spark_User",
    "Round_User",
    "Hash_User"];

no_document use_thys
  ["F_Spark_Obligation",
    "K_L_Spark_Obligation",
    "K_R_Spark_Obligation",
    "R_L_Spark_Obligation",
    "R_R_Spark_Obligation",
    "S_L_Spark_Obligation",
    "S_R_Spark_Obligation",
    "Round_Obligation",
    "Hash_Obligation"];
