theory Round_Declaration
imports Complex_Main

begin

type_synonym interfaces__unsigned_32' = " int "
type_synonym block_index' = " int "
type_synonym round_index' = " int "
record chain' = 
  h0'chain :: " int "
  h1'chain :: " int "
  h2'chain :: " int "
  h3'chain :: " int "
  h4'chain :: " int "
type_synonym block' = " int => int "
record chain_pair' = 
  left'chain_pair :: " chain' "
  right'chain_pair :: " chain' "
consts block___default_arr'' :: " block' "
consts block___default_arr_element'' :: " int "
consts block_index__base__first'' :: " int "
consts block_index__base__last'' :: " int "
consts block_index__first'' :: " int "
consts block_index__last'' :: " int "
consts block_index__size'' :: " int "
consts ca'' :: " int "
consts ca___init'' :: " int "
consts ca___loopinit'' :: " int "
consts cb'' :: " int "
consts cb___init'' :: " int "
consts cb___loopinit'' :: " int "
consts cc'' :: " int "
consts cc___init'' :: " int "
consts cc___loopinit'' :: " int "
consts cd'' :: " int "
consts cd___init'' :: " int "
consts cd___loopinit'' :: " int "
consts ce'' :: " int "
consts ce___init'' :: " int "
consts ce___loopinit'' :: " int "
consts chain___default_rcd'' :: " chain' "
consts chain__size'' :: " int "
consts chain_pair___default_rcd'' :: " chain_pair' "
consts chain_pair__size'' :: " int "
consts cla'' :: " int "
consts cla___init'' :: " int "
consts cla___loopinit'' :: " int "
consts clb'' :: " int "
consts clb___init'' :: " int "
consts clb___loopinit'' :: " int "
consts clc'' :: " int "
consts clc___init'' :: " int "
consts clc___loopinit'' :: " int "
consts cld'' :: " int "
consts cld___init'' :: " int "
consts cld___loopinit'' :: " int "
consts cle'' :: " int "
consts cle___init'' :: " int "
consts cle___loopinit'' :: " int "
consts cra'' :: " int "
consts cra___init'' :: " int "
consts cra___loopinit'' :: " int "
consts crb'' :: " int "
consts crb___init'' :: " int "
consts crb___loopinit'' :: " int "
consts crc'' :: " int "
consts crc___init'' :: " int "
consts crc___loopinit'' :: " int "
consts crd'' :: " int "
consts crd___init'' :: " int "
consts crd___loopinit'' :: " int "
consts cre'' :: " int "
consts cre___init'' :: " int "
consts cre___loopinit'' :: " int "
consts integer__base__first'' :: " int "
consts integer__base__last'' :: " int "
consts integer__first'' :: " int "
consts integer__last'' :: " int "
consts integer__size'' :: " int "
consts interfaces__unsigned_32__base__first'' :: " int "
consts interfaces__unsigned_32__base__last'' :: " int "
consts interfaces__unsigned_32__first'' :: " int "
consts interfaces__unsigned_32__last'' :: " int "
consts interfaces__unsigned_32__modulus'' :: " int "
consts interfaces__unsigned_32__size'' :: " int "
consts loop__1__j'' :: " int "
consts loop__1__j___init'' :: " int "
consts loop__1__j___loopinit'' :: " int "
consts rotate_amount__base__first'' :: " int "
consts rotate_amount__base__last'' :: " int "
consts rotate_amount__first'' :: " int "
consts rotate_amount__last'' :: " int "
consts rotate_amount__size'' :: " int "
consts round_index__base__first'' :: " int "
consts round_index__base__last'' :: " int "
consts round_index__first'' :: " int "
consts round_index__last'' :: " int "
consts round_index__size'' :: " int "
consts word__base__first'' :: " int "
consts word__base__last'' :: " int "
consts word__first'' :: " int "
consts word__last'' :: " int "
consts word__modulus'' :: " int "
consts word__size'' :: " int "
consts wordops__rotate_amount__base__first'' :: " int "
consts wordops__rotate_amount__base__last'' :: " int "
consts wordops__rotate_amount__first'' :: " int "
consts wordops__rotate_amount__last'' :: " int "
consts wordops__rotate_amount__size'' :: " int "
consts wordops__word__base__first'' :: " int "
consts wordops__word__base__last'' :: " int "
consts wordops__word__first'' :: " int "
consts wordops__word__last'' :: " int "
consts wordops__word__modulus'' :: " int "
consts wordops__word__size'' :: " int "
consts x'' :: " block' "
consts x___init'' :: " block' "
consts x___loopinit'' :: " block' "
consts bit__not' :: " [ int , int ] => int "
consts block___mk_const_arr' :: " int => block' "
consts character__pos' :: " int => int "
consts character__val' :: " int => int "
consts f_spark' :: " [ int , int , int , int ] => int "
consts int___abs' :: " int => int "
consts int___div' :: " [ int , int ] => int "
consts int___exp' :: " [ int , int ] => int "
consts int___mod' :: " [ int , int ] => int "
consts int___odd' :: " int => bool "
consts int___rem' :: " [ int , int ] => int "
consts int___times' :: " [ int , int ] => int "
consts int___to_real' :: " int => real "
consts k_l_spark' :: " int => int "
consts k_r_spark' :: " int => int "
consts r_l_spark' :: " int => int "
consts r_r_spark' :: " int => int "
consts real___abs' :: " real => real "
consts real___div' :: " [ real , real ] => real "
consts real___exp' :: " [ real , int ] => real "
consts real___minus' :: " [ real , real ] => real "
consts real___plus' :: " [ real , real ] => real "
consts real___times' :: " [ real , real ] => real "
consts real___uminus' :: " real => real "
consts round__' :: " real => int "
consts s_l_spark' :: " int => int "
consts s_r_spark' :: " int => int "
consts wordops__rotate' :: " [ int , int ] => int "

end
