(*
  no_document use_thy "ThisTheory";
  use_thy "ThatTheory";
*)

tolerate_legacy_features := false;

no_document use_thy "LList";
no_document use_thy "Maybe";
no_document use_thy "Nats";
use_thy "LFPFusion";
use_thy "WorkerWrapper";
use_thy "CounterExample";
use_thy "WorkerWrapperNew";
use_thy "Accumulator";
use_thy "UnboxedNats";
use_thy "Streams";
use_thy "Continuations";
no_document use_thy "Backtracking";
no_document use_thy "Nub";
no_document use_thy "Last";
