no_document use_thys [
  "~~/src/HOL/Library/Lattice_Algebras"
];

use_thys [
  "~~/src/HOL/Library/Float"
];

no_document use_thys [
  "~~/src/HOL/Decision_Procs/Approximation",
  "~~/src/HOL/Library/FrechetDeriv"
];

use_thys [
  "Bounded_Continuous_Function",
  "Initial_Value_Problem",
  "Picard_Lindeloef_Qualitative",
  "One_Step_Method",
  "Runge_Kutta",
  "Runge_Kutta_Ex",
  "Runge_Kutta_Ex2"
];
