#!/usr/bin/env bash
#
# $Id: cvs-sync,v 1.14 2009-09-06 15:14:25 lsf37 Exp $
# Author: Gerwin Klein, NICTA
#
# Cron job that synchronizes HEAD with release branch.
# Tested on sunbroy2 only.
# 

. ~/.bashrc

HEAD=~/afp/devel
BRANCH_TAG=Isabelle2009
SYNC_TAG=last_autosync
SYNC_MSG="auto sync with $BRANCH_TAG"
MODULES="thys web admin doc"

function fail()
{
  echo "$1" >&2
  exit 2
}

cd $HEAD || fail "Could not cd to $HEAD"
# update
cvs -Q up -d -A || fail "Error updating; aborting sync"
# sync, no keyword expansion
cvs -Q up -d -kk -j $SYNC_TAG -j $BRANCH_TAG || fail "Error merging; aborting sync"
# check for conflicts
cvs -Q up -d -A || fail "Conflicts found; aborting sync"
# commit back changes on HEAD
cvs -Q commit -m "$SYNC_MSG" || fail "Error committing changes"
# move SYNC_TAG
cvs -Q rtag -r $BRANCH_TAG -F $SYNC_TAG $MODULES || fail "Could not move sync tag"

