#!/usr/bin/env bash
#
# $Id: devel-copy,v 1.4 2007-09-10 21:39:26 lsf37 Exp $
# Author: Gerwin Klein, NICTA
#
# Cron job that copies development snapshot to SF.
# Tested on sunbroy2 only.
# 

SOURCE=~isatest/html-data/afp/
TARGET=lsf37@shell.sf.net:afp-web/htdocs/

/usr/local/bin/rsync -rplqz $SOURCE $TARGET
