#!/usr/bin/env bash
#
# Author: Gerwin Klein, NICTA
#
# Cron job that copies development snapshot to SF.
# 

#SOURCE=~isatest/html-data/afp/
SOURCE=~/afp/web/
TARGET=lsf37,afp@web.sourceforge.net:htdocs/

/usr/bin/rsync -vrplqz $SOURCE $TARGET
