#!/usr/bin/env bash
#
# $Id: devel-copy,v 1.3 2007-09-01 04:35:06 lsf37 Exp $
# Author: Gerwin Klein, NICTA
#
# Cron job that copies development snapshot to SF.
# Tested on sunbroy2 only.
# 

SOURCE=~isatest/html-data/afp/
TARGET=lsf37@shell.sf.net:afp-web/htdocs/

/usr/local/bin/rsync -rplqzn $SOURCE $TARGET