#!/usr/bin/env bash
#
# Author: Gerwin Klein, NICTA
#
# Prepare a separate copy of Isabelle development snapshot for AFP test.
#

## This script is only relevant for the development version
WORKING_COPY=~/afp/devel


## functions

function fail()
{
  echo "$1" >&2
  log "FAILED, $1"
  exit 2
}

## main

. $WORKING_COPY/admin/main-config || fail "could not read main-config."

[ -d $DISTPREFIX ] || fail "$DISTPREFIX is not a directory."

export DISTPREFIX
export SCALA_HOME=$AFP_CONTRIB/scala

rm -rf $DISTPREFIX/dist-*
rm -rf $DISTPREFIX/Isabelle*
rm -f $DISTPREFIX/ISABELLE*
$ISA_ADMIN/makedist >> $DISTLOG 2>&1

ISABELLE_DIST=$(cat $DISTPREFIX/ISABELLE_DIST)

tar xz -C $DISTPREFIX -f $ISABELLE_DIST

ISABELLE_NAME=$(basename $ISABELLE_DIST)
ISABELLE_DIR=${ISABELLE_NAME%.tar.gz}
ln -s $ISABELLE_DIR $ISABELLE_DEVEL
rm -rf $ISABELLE_DEVEL/contrib
ln -s $AFP_CONTRIB $ISABELLE_DEVEL/contrib

cat $ISA_SETTINGS/$SHORT >> $ISABELLE_DEVEL/etc/settings

cd $ISABELLE_DEVEL/src/HOL
../../bin/isabelle make HOL >> $DISTLOG 2>&1

#$ISABELLE_DEVEL/build -b HOL >> $DISTLOG
