#!/usr/bin/env bash

# standard invocation of afp_site_gen

set -e

source "$(dirname "$0")/common"

while getopts "t:r:" OPT
do
    case "$OPT" in
      r)
        AFP_VERSION="$OPTARG"
        ;;
      t)
        ISABELLE_TOOL="$OPTARG"
        ;;
    esac
done
shift $(($OPTIND-1))

set_isabelle_tool

"$ISABELLE_TOOL" afp_publish "$@"
