#!/usr/bin/env bash
#
# Author: Gerwin Klein, NICTA
#
# Automated regression test to be run from cron.
# Sends email to maintainers if test fails.
#
# Relies on being run in the isatest environment.
# 

. ~/.bashrc

## settings

ISABELLE_RELEASES=/home/isabelle
ISABELLE_DEVEL=~/isadist/Isabelle
ISABELLE_IDENT=~/isadist/ISABELLE_IDENT
WORKING_COPY=~/afp
DATE=$(date "+%Y-%m-%d")

LOG=~/afp-log/afp-test
MASTERLOG=~/afp-log/afp-test.log
REPORT=~/afp-log/report

SHORT=at-poly-test
SETTINGS=~/settings/$SHORT

function fail()
{
  echo "$1" >&2
  exit 2
}

TMP=`mktemp -q /tmp/afp-regression.mail.XXXXXX` \
 || fail "could not make tmp file"

#

PRG="$(basename "$0")"

## functions

function usage()
{
  echo
  echo "Usage: $PRG [-f] [-|release_tag]"
  echo
  echo "  Runs testall from cron and logs output"
  echo
  echo "Options: -f   only run test that are marked as frequent"
  echo 
  exit 1
}

## 

if [ "$1" == "-f" ]; then
	FRQ="-f"
	shift
fi

[ "$#" != "1" -o "$1" = "-?" ] && usage

if [ "$1" == "-" ]; then
  AFP_VER="development"
  WORKING_COPY=$WORKING_COPY/devel
  ISABELLE_TOOL=$ISABELLE_DEVEL/bin/isabelle

  ERRORDIR=$HOME/var
  RUNNING=$HOME/var/running
  if [ -f "$RUNNING/$SHORT.running" -o -e $ERRORDIR/$SHORT*.log ]; then
    echo "`date` $HOSTNAME: Skipped test. Isabelle devel version broken." >> $MASTERLOG
    exit 1
  fi
  cat $SETTINGS >> $ISABELLE_DEVEL/etc/settings
  ML_IDENTIFIER=`$ISABELLE_TOOL getenv -b ML_IDENTIFIER` || fail "could not identify ML system"
  export ISABELLE_IMAGE_PATH="$HOME/isabelle-$SHORT/heaps/$ML_IDENTIFIER/"
  
  if [ ! -r "$ISABELLE_IMAGE_PATH/HOL" -o ! -r "$ISABELLE_IMAGE_PATH/HOLCF" ]; then
    echo "`date` $HOSTNAME: Skipped test. Isabelle devel version broken (HOL or HOLCF image not readable)." 
    exit 1
  fi
  
  LOG=$LOG-devel-$DATE.log
  SNAPSHOT=1;
  REPORT=$REPORT-devel

  BROWSER_INFO=`$ISABELLE_TOOL getenv -b ISABELLE_BROWSER_INFO` || fail "could not find browser info"
  [ -e "$BROWSER_INFO" ] && rm -rf $BROWSER_INFO

  ISABELLE_HG_ID="$(cat $ISABELLE_IDENT)"
  ISABELLE_VER="devel -- hg id $ISABELLE_HG_ID"
else
  AFP_VER="release ($1)"
  WORKING_COPY=$WORKING_COPY/release
  ISABELLE_TOOL=$ISABELLE_RELEASES/$1/bin/isabelle
  ML_IDENTIFIER=`$ISABELLE_TOOL getenv -b ML_IDENTIFIER` || fail "could not identify ML system"
  export ISABELLE_IMAGE_PATH="$ISABELLE_RELEASES/$1/heaps/$ML_IDENTIFIER/"
  LOG=$LOG-$1-$DATE.log
  REPORT=$REPORT-$1
  
  ISABELLE_VER="release -- $($ISABELLE_TOOL version)"
fi

. $WORKING_COPY/admin/main-config || fail "could not read main-config."
MAIL=$WORKING_COPY/admin/mail-attach

echo "Start test for $WORKING_COPY at `date`, $HOSTNAME" > $LOG
echo >> $LOG
echo "begin hg pull/update" >> $LOG

# hg pull -u to newest version of archive 
cd $WORKING_COPY || fail "could not cd to $WORKING_COPY"
hg pull -u -q >> $LOG 2>&1 || fail "could not hg pull."

echo "end hg pull/update" >> $LOG
echo >> $LOG

AFP_HG_ID="$(hg id -i)"
AFP_VERSION="AFP version: $AFP_VER -- hg id $AFP_HG_ID"
ISA_VERSION="Isabelle version: $ISABELLE_VER"

echo "$AFP_VERSION" >> $LOG
echo "$ISA_VERSION" >> $LOG
echo >> $LOG

# run test
$WORKING_COPY/admin/testall $FRQ -t $ISABELLE_TOOL -c >> $LOG 2>&1
FAILURE=$?

ELAPSED=$("$HOME/bin/showtime" "$SECONDS")

echo >> $LOG
echo "End test on `date`, $HOSTNAME, elapsed time: $ELAPSED" >> $LOG

# generate report
DIFF=`$WORKING_COPY/admin/report.pl $LOG $REPORT`

# send mail on status changes
if [ -n "$DIFF" ]; then
  cat > $TMP <<EOF
The status of the following AFP entries changed or remains FAIL: 
$DIFF

$AFP_VERSION
$ISA_VERSION
Test ended on: $HOSTNAME, `date`.

Have a nice day,
  isatest

EOF
  for R in $MAIN_NOTIFY; do
    $MAIL 'status (AFP)' "$R" $TMP $REPORT $LOG
  done  
fi

# send email to maintainer if there was a problem
if [ "$FAILURE" != "0" ]; then
  FAIL=`tail -4 $LOG | head -1`
  echo "`date`, $HOSTNAME, $AFP_VER [afp: $AFP_HG_ID, isa: $ISABELLE_VER]: test failed on [$FAIL]. Elapsed time: $ELAPSED" >> $MASTERLOG
  for E in $FAIL; do
    (
      . $WORKING_COPY/thys/$E/config || fail "error reading config for $E"
      if [ "$FREQUENT" == "yes" ]; then
        cat > $TMP <<EOF
Session [$E] in the automated afp test failed. 

$AFP_VERSION
$ISA_VERSION
Test ended on: $HOSTNAME, `date`.

To reproduce the error, check out the $AFP_VER version of the
archive from sourceforge and run "isabelle make" on your session.

This is an automatically generated email. To switch off these 
notifications, edit thys/$E/config and hg commit and push the changes.

Have a nice day,
  isatest

EOF
        for R in $NOTIFY; do
          $MAIL 'test failed (Archive of Formal Proofs)' "$R" $TMP $LOG
        done
      fi
    )
  done
else
  echo "`date`, $HOSTNAME, $AFP_VER [afp: $AFP_HG_ID, isa: $ISABELLE_VER]: All tests successful. Elapsed time: $ELAPSED" >> $MASTERLOG
fi

# clean up tmp
rm -f $TMP

# make devel snapshot
if [ "$SNAPSHOT" == "1" ]; then
    echo "`date`: start preparing devel snapshot" >> $LOG
    EXPORT=afp-devel
    STATUS=entry-status.txt
    WEB=~/html-data/afp
    AFPRELEASE=$WEB/release
    mkdir -p $AFPRELEASE
    cp $REPORT $AFPRELEASE/$STATUS
    hg archive -q -I thys -I web $EXPORT
    
    # update status report
    cp $REPORT $EXPORT/$STATUS
    echo >> $EXPORT/$STATUS
    echo `date` >> $EXPORT/$STATUS

    # make devel tar files
    tar cf $EXPORT.tar $EXPORT/thys
    gzip --best -f $EXPORT.tar
    mv $EXPORT.tar.gz $AFPRELEASE

    cd $EXPORT/thys
    for DIR in `ls -d *`; do
        if [ -d $DIR ]; then
            TF=afp-$DIR-devel.tar
            tar -cf $TF $DIR
            gzip --best -f $TF
            mv $TF.gz $AFPRELEASE
        fi
    done
    cd ../..    

    # prepare development entries
    DEVENTRIES=$WEB/devel-entries
    mkdir -p $DEVENTRIES
    cp -r $EXPORT/web/entries/* $DEVENTRIES
    perl -pi -e "s:browser_info/current/:browser_info/devel/:g" $DEVENTRIES/*.shtml
    perl -pi -e "s:current.tar.gz:devel.tar.gz:g" $DEVENTRIES/*.shtml
    VERSION=$(env LC_ALL=C date "+%d-%b-%Y")
    perl -pi -e "s:-VERSION-:Isabelle-$VERSION:g" $DEVENTRIES/*.shtml
    perl -pi -e "s:-INCLUDE-:#include:g" $DEVENTRIES/*.shtml
    # inefficient. should write a perl script that does this all at once.
    for F in $DEVENTRIES/*.shtml; do
        BASE=$(basename $F)
        ENTRY=${BASE%.shtml}
        LINE=$(grep ^$ENTRY: $REPORT) 
        STATUS=${LINE#"$ENTRY: "}
        if [ "$STATUS" != "" ]; then
            perl -pi -e "s:-STATUS-:$STATUS:g" $F
        fi
    done
    cp $EXPORT/web/index.shtml $WEB/devel.shtml
    perl -pi -e "s:entries/:devel-entries/:g" $WEB/devel.shtml
      
    # prepare generated html
    BROWSER_DEVEL=$WEB/browser_info/devel
    mkdir -p $BROWSER_DEVEL
    cp -r $BROWSER_INFO/* $BROWSER_DEVEL

    # fix permissions
    chmod -R g=u $WEB
    chmod -R a+r $WEB
    find $WEB -type d | xargs chmod g+s
    find $WEB -type d | xargs chmod a+x

    # clean up export dir, leave prepared pages in $WEB
    rm -rf $EXPORT
    
    echo "`date`: finished preparing devel snapshot" >> $LOG
fi
