#!/usr/bin/env bash

# devel invocation of sitegen.py

STATUS_FILE="$(readlink -f "$1")"
shift

cd "$(dirname "$0")/.."

admin/sitegen-lib/sitegen.py --dest=web --metadata=metadata --status="$STATUS_FILE" thys $@

mkdir -p release
echo "Packing tars ..."

find thys -mindepth 1 -maxdepth 1 -type d | while read LINE; do
  ENTRY="$(basename "$LINE")"
  tar -C thys -czf "release/afp-${ENTRY}-current.tar.gz" "$ENTRY"
done
