#!/usr/bin/env bash
#
# $Id: testall,v 1.8 2008-10-04 14:29:42 makarius Exp $
# Author: Gerwin Klein, NICTA
#
# Tests all entries in Archive of Formal Proofs
# 

## settings

function usage()
{
  echo
  echo "Usage: $PRG OPTIONS [entries]"
  echo
  echo "  Runs isatool make on specified entries in the Archive of Formal Proofs"
  echo 
  echo "Options:"
  echo "-t <path/to/isatool>   use isatool at specified path"     
  echo "-c                     include target clean (rebuild session)"
  echo "-d <path>              use specified path as base for archive entries"
  echo "-r                     use env variable ISABELLE_RELEASES to find isatool"
  echo "-f                     only test entries marked as frequent"
  echo 
  echo "Examples:"
  echo
  echo "$PRG"
  echo   "uses isatool in your normal path to run all tests (usually = devel version)"
  echo
  echo "$PRG Example-Submission"
  echo   "same as above, but only test Example-Submission"
  echo
  echo "$PRG -t /usr/proj/isabelle/Isabelle2003/bin/isatool Example-Submission"
  echo   "uses the Isabelle 2003 release version to run the test"
  echo
  echo "$PRG -r Isabelle2003 Example-Submission"
  echo   "uses the distribution $ISABELLE_RELEASES/Isabelle2003 to test Example-Submission"
  exit 1
}

function fail()
{
  echo "$1" >&2
  exit 2
}

function check_isatool()
{
  [ -x $ISABELLE_TOOL ] || fail "No isatool found at [$ISABELLE_TOOL]."
  ML_IDENTIFIER=`$ISABELLE_TOOL getenv -b ML_IDENTIFIER` || fail "could not identify ML system"
  ISABELLE_HOME=`$ISABELLE_TOOL getenv -b ISABELLE_HOME` || fail "could not find Isabelle home"
  [ -n "$ISABELLE_IMAGE_PATH" ] || export ISABELLE_IMAGE_PATH="$ISABELLE_HOME/heaps/$ML_IDENTIFIER/"
}

## 

PRG="$(basename "$0")"
THYS="$(dirname "$0")/../thys"

[ "$1" = "-?" ] && usage

ISABELLE_TOOL=isatool
FRQONLY="no"

while getopts "t:cfr:d:" OPT
do
    case "$OPT" in
      r)
        [ "$ISABELLE_RELEASES" == "" ] && fail "ISABELLE_RELEASES not set"
        ISABELLE_TOOL="$ISABELLE_RELEASES/$OPTARG/bin/isatool"
        check_isatool
        ;;
      c)
        CLEAN="clean"
        ;;
      d)
        THYS="$OPTARG"
        ;;
      t)
        ISABELLE_TOOL="$OPTARG"
        check_isatool
        ;;
      f) 
        FRQONLY="yes"
        ;;
    esac
done

shift $(($OPTIND - 1))

[ -d $THYS ] || fail "Could not find archive directory. Tried [$THYS]."
cd $THYS

DIRS=$@
if [ "$DIRS" == "" ]; then DIRS=*; fi

FAIL="";

for DIR in $DIRS; do
    if [ -d $DIR -a "$DIR" != "CVS" ]; then
        cd $DIR
        if [ "$FRQONLY" == "no" ] || (unset FREQUENT; . ./config; [ "$FREQUENT" == "yes" ]); then
          echo "Testing [$DIR]"
          $ISABELLE_TOOL make $CLEAN all $@ || FAIL="${FAIL}${DIR} "
          echo "Finished [$DIR]"
        fi
        cd ..
    fi
done

if [ "$FAIL" != "" ]; then 
    echo "The following tests failed:"
    echo "$FAIL"
    echo "Please check logs."
    exit 1
else
    echo "All tests successful."
    exit 0
fi

