#!/usr/bin/env bash

# Quadrotor
gnuplot -c plot_arch_comp.plg out_quadrot  t 0 5 "altitude x_3" -0.6 1.5

# Laub Loomis
gnuplot -c plot_arch_comp.plg out_ll_001 t 0 20 "x_4" 1.5 4.5
gnuplot -c plot_arch_comp.plg out_ll_01  t 0 20 "x_4" 1.5 5

# Van der Pol
gnuplot -c plot_arch_comp.plg out_p1_vdp_0 x -2.5 2.5 y -3 3

# Space Rendezvous
cat out_space_p2.out | grep -E '0x000000|^$' > out_space_p2_pos.out
cat out_space_p2.out | grep -E '0x0000ff|^$' > out_space_p2_vel.out
cat {out_space_p1,out_space_p2_pos,out_space_passive}.out > out_space.out
gnuplot -c plot_arch_comp.plg out_space x -1000 250 y -500 0

cat {out_space_p2_vel,out_space_p2_v_red}.out > out_space_vel.out
echo "$(cat plot_arch_comp.plg),\\" > plot_arch_comp_circle.plg
echo 'sqrt(9.9-x*x) title "v_x^2 + v_y^2 = 3.3^2"' >> plot_arch_comp_circle.plg
gnuplot -c plot_arch_comp_circle.plg out_space_vel "v_x" 2 4 "v_y" 0.25 2.25
