(* if you'd like to build on other archive entries (here "Example"), use:
add_path "../Example";
*)

(* to suppress document generation of some theories, use:
no_document use_thy "ThisTheory";
*)

(* for normal theory loading, use:
use_thy "ThatTheory";
*)

no_document use_thy "Multiset";
no_document use_thy "Misc";
no_document use_thy "Permutation";
no_document use_thy "Interleave";

use_thy "MainResult";
