build:
	mlton -profile time -default-type intinf Complementation.mlb
run:
	./Complementation
profile:
	mlprof Complementation mlmon.out
clean:
	rm Complementation mlmon.out

.PHONY: build run profile clean
