(*   *)
no_document use_thys [
  "Tools/Imperative_HOL_Add", 
  "Tools/Syntax_Match",
  "../Collections/common/HashCode",
  "../Collections/common/Misc",
  "Tools/Sep_Misc",
  "~~/src/HOL/Library/Efficient_Nat"
];

use_thys ["Sep_Main",
         "Examples/Imp_List_Spec",
         "Examples/List_Seg", "Examples/Open_List","Examples/Circ_List",
         "Examples/Imp_Map_Spec", "Examples/Hash_Map_Impl", 
         "Examples/Imp_Set_Spec", "Examples/Hash_Set_Impl",
         "Examples/To_List_GA",
         "Examples/Union_Find",
         "Examples/Idioms"];
