#!/usr/bin/env bash
#
# Author: Makarius
#
# DESCRIPTION: update central ROOT file in AFP/thys


## diagnostics

PRG="$(basename "$0")"

function usage()
{
  echo
  echo "Usage: isabelle $PRG"
  echo
  echo "  Update central $AFP/ROOT"
  echo "  based on ROOT file in each subdirectory."
  echo
  exit 1
}

function fail()
{
  echo "$1" >&2
  exit 2
}


## process command line

[ "$#" -eq 0 ] || usage


## main

(
  cd "$AFP" || fail "Bad directory: \"$AFP\""
  rm -f ROOT
  export LC_COLLATE=C
  for DIR in *
  do
    if [ -f "$DIR/ROOT" ]; then
      {
        echo "(** !!! COPY of $DIR/ROOT !!! **)"
        perl -p -e 's/ in "\."//g;' "$DIR/ROOT"
        echo
      } >> ROOT
    fi
  done
)
