title = "Complete Elliptic Integrals and the Arithmetic–Geometric Mean"
date = 2026-07-03
topics = [
  "Mathematics/Analysis",
]
abstract = """
<p>This entry builds up two theories and connects them. The first consists of the <em>complete elliptic integrals</em> of the first and second kind
\\[
\\begin{aligned}
K(x) &= \\int_0^{\\frac{\\pi}{2}} (1-x \\sin(t)^2)^{-\\frac{1}{2}}\\,\\text{d}t\\\\
E(x) &= \\int_0^{\\frac{\\pi}{2}} (1-x \\sin(t)^2)^{\\frac{1}{2}}\\,\\text{d}t
\\end{aligned}
\\]
for real or complex $x$.</p>
<p>The second one is the <em>arithmetic-geometric mean</em> function $\\text{agm}(x,y)$, which is defined as the limit of the sequence obtained by replacing the pair $(x,y)$ with the pair consisting of the arithmetic and geometric means of $x$ and $y$, i.e. $(x,y)\\mapsto (\\frac{1}{2}(x+y), \\sqrt{xy})$.</p>
<p>The two theories are then connected by proving (among other things) that:
\\[\\text{agm}(a,b) = \\frac{\\pi a}{2K((a^2-b^2)/a^2)}\\]
</p>
<p>Various other important properties are shown, e.g.:</p>
<ul>
<li>Continuity, derivatives, antiderivatives of $K$ and $E$ as well as their relation to the hypergeometric function ${}_2 F_{1}$</li>
<li>Legendre's identity \\[K(x) E(1-x) + E(x) K(1-x) - K(x) K(1-x) = \\frac{\\pi}{2}\\]</li>
<li>The convergence of the AGM iterations, including uniform convergence and an estimate of the speed of convergence</li>
<li>Upward and downward identities for $K$ and $E$, e.g. \\[K(x^2) = \\frac{K\\left(\\frac{4x}{(1+x)^2}\\right)}{1+x}\\]</li>
<li>The relationship of the AGM to the Jacobi theta functions</li>
<li>The Brent–Salamin algorithm to approximate $\\pi$ via AGM iterations (abstractly, without rounding error analysis)</li>
</ul>"""
license = "bsd"
note = ""
creation_note = ""

[authors]

[authors.eberl]
email = "eberl_email"

[contributors]

[notify]
eberl = "eberl_email"

[history]

[extra]

[related]
dois = []
pubs = []
