title = "Combinatorial q-Analogues"
date = 2024-12-02
topics = [
  "Mathematics/Number theory",
]
abstract = """
<p>This entry defines the $q$-analogues of various combinatorial symbols, namely:</p>
<ul>
<li>The $q$-bracket $[n]_q = \\frac{1-q^n}{1-q}$ for $n\\in\\mathbb{Z}$</li>
<li>The $q$-factorial $[n]_q! = [1]_q [2]_q \\cdots [n]_q$ for $n\\in\\mathbb{Z}$</li>
<li>The $q$-binomial coefficients $\\binom{n}{k}_{\\!q} = \\frac{[n]_q!}{[k]_q!\\,[n-k]_q!}$ for $n,k\\in\\mathbb{N}$ (also known as
        Gaussian binomial coefficients or Gaussian polynomials)</li>
<li>The infinite $q$-Pochhammer symbol $(a; q)_\\infty = \\prod_{n=0}^\\infty\\, (1 - aq^n)$</li>
<li>Euler's $\\phi$ function $\\phi(q) = (q; q)_\\infty$</li>
<li>The finite $q$-Pochhammer symbol $(a; q)_n = (a; q)_\\infty / (aq^n; q)_\\infty$ for $n\\in\\mathbb{Z}$</li>
</ul>
<p>
Proofs for many basic properties are provided, notably for the $q$-binomial theorem:</p>
\\[(-a; q)_n = \\prod_{k=0}^{n-1} (1 + aq^n) = \\sum_{k=0}^n \\binom{n}{k}_{\\!\\!q} a^k q^{k(k-1)/2} \\]
<p>
Additionally, two identities of Euler are formalised that give power series expansions for
$(a; q)_\\infty$ and $1/(a; q)_\\infty$ in powers of $a$:</p>
\\[
\\begin{alignat*}{3}
(a; q)_\\infty &{}= \\prod_{k=0}^\\infty (1 - aq^k) &{}= 
      \\sum_{n=0}^\\infty \\frac{(-a)^n q^{n(n-1)/2}}{(1-q) \\cdots (1-q^n)}\\\\
\\frac{1}{(a; q)_\\infty} &{}= \\prod_{k=0}^\\infty \\frac{1}{1 - aq^k} &{}= 
      \\sum_{n=0}^\\infty \\frac{a^n}{(1-q)\\cdots(1-q^n)}
\\end{alignat*}
\\]"""
license = "bsd"
note = ""

[authors]

[authors.eberl]
email = "eberl_email"

[contributors]

[notify]
eberl = "eberl_email"

[history]

[extra]

[related]
dois = []
pubs = []
