title = "Dedekind Sums"
date = 2025-04-23
topics = [
  "Mathematics/Number theory",
]
abstract = """
<p>For integers $h$, $k$, the Dedekind sum is defined as
\\[s(h,k) = \\sum_{r=1}^{k-1} \\frac{r}{k} \\left(\\left\\{\\frac{hr}{k}\\right\\} - \\frac{1}{2}\\right) \\]
where $\\{x\\} = x - \\lfloor x\\rfloor$ denotes the fractional part of $x$.</p>
<p>These sums occur in various contexts in analytic number theory, e.g. in the functional
equation of the Dedekind $\\eta$ function or in the study of modular forms.</p>
<p>We give the definition of $s(h,k)$ and prove its basic properties, including the reciprocity law
\\[s(h,k) + s(k,h) = \\frac{1}{12hk} + \\frac{h}{12k} + \\frac{k}{12h} - \\frac{1}{4} \\]
and various congruence results.</p>
<p>Our formalisation follows Chapter 3 of Apostol's
<em>Modular Functions and Dirichlet Series in Number Theory</em> and contains
all facts related to Dedekind sums from it (without the exercises).</p>"""
license = "bsd"
note = ""

[authors]

[authors.eberl]
email = "eberl_email"

[authors.bordg]
email = "bordg_email"

[authors.paulson]
email = "paulson_email"

[authors.li]
email = "li_email"

[contributors]

[notify]
eberl = "eberl_email"

[history]

[extra]

[related]
dois = [
  "10.4230/LIPIcs.ITP.2024.40",
]
pubs = []
