title = "Complex Lattices, Elliptic Functions, and the Modular Group"
date = 2025-05-22
topics = [
  "Mathematics/Number theory",
]
abstract = """
<p>This entry defines complex lattices, i.e. $\\Lambda(\\omega_1,\\omega_2) = \\mathbb{Z}\\omega_1 + \\mathbb{Z}\\omega_2$ where $\\omega_1/\\omega_2\\notin\\mathbb{R}$.
Based on this, various other related topics are covered:</p>
<ul>
  <li>the modular group $\\Gamma$ and its fundamental region</li>
  <li>elliptic functions and their basic properties</li>
  <li>the Weierstra&szlig; elliptic functions $\\wp$, $\\sigma$, $\\zeta$ and many identities about them</li>
  <li>the Eisenstein series $G_n$ (including the &ldquo;forbidden&rdquo; series $G_2$)</li>
  <li>the ODE satisfied by $\\wp$ and the corresponding recurrence relation for $G_n$</li>
  <li>the lattice invariants $g_2$, $g_3$, Klein's $J$ invariant, and the elliptic modulus $\\lambda$</li>
  <li>the non-vanishing of the lattice discriminant $\\Delta$</li>
  <li>the quasiperiods $\\eta_1$ and $\\eta_2$, Legendre's relation, and their connection to $G_2$</li>
  <li>$G_n$, $\\Delta$, $J$, $\\lambda$ as holomorphic functions in the upper half plane and the Fourier expansions of the first three</li>
  <li>Dedekind's $\\eta$ function and its connection to $G_2$ and $\\Delta$</li>
  <li>the functional equations of $G_n$, $\\Delta$, $J$, and $\\eta$ w.r.t. the modular group</li>
  <li>the inversion formulas for the Jacobi theta functions and their connection to all of the above</li>
</ul>
<p>In particular, this entry contains most of Chapters 1 and 3 from Apostol's
<em><a href=\"https://doi.org/10.1007/978-1-4612-0999-7\">Modular Functions and Dirichlet Series in Number Theory</a></em> and parts of Chapter 2.
The purpose of this entry is to provide a foundation for further formalisation of
modular functions and modular forms.</p>"""
license = "bsd"
note = ""
creation_note = ""

[authors]

[authors.eberl]
email = "eberl_email"

[authors.bordg]
email = "bordg_email"

[authors.li]
email = "li_email"

[authors.paulson]
email = "paulson_email"

[contributors]

[notify]
eberl = "eberl_email"

[history]

[extra]

[related]
dois = [
  "10.1007/978-1-4612-0999-7",
  "10.1007/978-1-4612-4752-4",
  "10.4230/LIPIcs.ITP.2024.40",
]
pubs = []
