title = "Tarski's Parallel Postulate implies the 5th Postulate of Euclid, the Postulate of Playfair and the original Parallel Postulate of Euclid"
date = 2021-01-31
topics = [
  "Mathematics/Geometry",
]
abstract = """
<p>The <a href=\"https://geocoq.github.io/GeoCoq/\">GeoCoq library</a>  contains a formalization
of geometry using the Coq proof assistant. It contains both proofs
about the foundations of geometry and high-level proofs in the same
style as in high school.  We port a part of the GeoCoq
2.4.0 library to Isabelle/HOL: more precisely,
the files Chap02.v to Chap13_3.v, suma.v as well as the associated
definitions and some useful files for the demonstration of certain
parallel postulates. The synthetic approach of the demonstrations is directly
inspired by those contained in GeoCoq. The names of the lemmas and
theorems used are kept as far as possible as well as the definitions.
</p>
<p>It should be noted that T.J.M. Makarios has done
<a href=\"https://www.isa-afp.org/entries/Tarskis_Geometry.html\">some proofs in Tarski's Geometry</a>. It uses a definition that does not quite
coincide with the definition used in Geocoq and here.
Furthermore, corresponding definitions in the <a href=\"https://www.isa-afp.org/entries/Poincare_Disc.html\">Poincaré Disc Model
development</a> are not identical to those defined in GeoCoq.
</p>
<p>In the last part, it is
formalized that, in the neutral/absolute space, the axiom of the
parallels of Tarski's system implies the Playfair axiom, the 5th
postulate of Euclid and Euclid's original parallel postulate. These
proofs, which are not constructive, are directly inspired by Pierre
Boutry, Charly Gries, Julien Narboux and Pascal Schreck.
</p>"""
license = "lgpl"
note = ""

[authors]

[authors.coghetto]
email = "coghetto_email"

[contributors]

[notify]
coghetto = "coghetto_email"

[history]
2021-01-31 = """
Initial Version
INITIAL:

CREATE: Tarski_Neutral.thy
==========================

locale Tarski_neutral_dimensionless
locale Tarski_2D

context Tarski_neutral_dimensionless

Definitions (with arity left,right)
-----------------------------------
WARNING: Perp2(1,4): GeoCoq Perp2 A B C D E :: IsaGeoCoq E Perp2 A B C D

OFSC(4,4) Cong3(3,3) Col(0,3) Bet4(0,4) BetS(0,3) FSC(4,4) IFSC(4,4)
Le(2,2) Lt(2,2) Ge(2,2) Gt(2,2) Out(1,2) Midpoint(1,2) Per(0,3) PerpAt(1,4)
Perp(2,2) Coplanar(0,4) TS(2,2) ReflectL(2,2) Reflect(2,2) InAngle(1,3)
ParStrict(2,2) Par(2,2) Plg(0,4) ParallelogramStrict(0,4)
ParallelogramFlat(0,4) Parallelogram(0,4) Rhombus(0,4) Rectangle(0,4)
Square(0,4) Lambert(0,4) OS(0,4) TSP(3,2) OSP(3,2) Saccheri(0,4)
ReflectLAt(1,4) ReflectAt(1,4) upper_dim_axiom[UpperDimAxiom](0,0)
all_coplanar_axiom[AllCoplanarAxiom](0,0) CongA(3,3) LeA(3,3) LtA(3,3)
GtA(3,3) Acute(0,3) Obtuse(0,3) OrthAt(1,4) Orth(3,3) SuppA(3,3) SumA(6,3)
TriSumA(3,3) SAMS(0,6) Inter(1,4) Perp2(1,4) QCong(0,1) TarskiLen(0,3)
QCongNull(0,1) QCongA(0,1) Ang(3,1) QCongAAcute(0,1) AngAcute(3,1)
QCongANullAcute(0,1) QCongAnNull(0,1) QCongAnFlat(0,1) IsNullAngaP(0,1)
QCongANull(0,1) AngFlat(0,1)
tarski_s_parallel_postulate[TarskiParallelPostulate](0,0)
euclid_5[Euclid5](0,0)
euclid_s_parallel_postulate[EuclidSParallelPostulate](0,0)
playfair_s_postulate[PlayFairSPostulate](0,0)

Porting Files
-------------

theories/Main/Tarski_dev/Ch02_cong.v
theories/Main/Tarski_dev/Ch03_bet.v
theories/Main/Tarski_dev/Ch04_col.v
theories/Main/Tarski_dev/Ch04_cong_bet.v
theories/Main/Tarski_dev/Ch05_bet_le.v
theories/Main/Tarski_dev/Ch06_out_lines.v
theories/Main/Tarski_dev/Ch07_midpoint.v
theories/Main/Tarski_dev/Ch08_orthogonality.v
theories/Main/Tarski_dev/Ch09_plane.v
theories/Main/Tarski_dev/Ch10_line_reflexivity.v
theories/Main/Tarski_dev/Ch10_line_reflexivity_2.v
theories/Main/Tarski_dev/Ch11_angles.v
theories/Main/Annexes/suma.v
theories/Main/Tarski_dev/Ch12_parallel.v
theories/Main/Tarski_dev/Ch12_parallel_inter_dec.v
theories/Main/Tarski_dev/Ch13_1.v
theories/Main/Tarski_dev/Ch13_2_length.v
theories/Main/Tarski_dev/Ch13_3_angles.v
theories/Main/Meta_theory/Parallel_postulates/euclid_5_original_euclid.v
theories/Main/Meta_theory/Parallel_postulates/tarski_euclid.v
theories/Main/Meta_theory/Parallel_postulates/tarski_playfair.v

(revision f5710bbb2d80) <br>
"""

2025-04-18 = """
Split Tarski_Neutral.thy into 3 files:
  Tarski_Neutral.thy
  Tarski_Neutral_2D.thy
  Tarski_Postulate_Parallels.thy
Modify ROOT
Move locale Tarski_neutral_2D and 2D-lemma to Tarski_Neutral_2D.thy
Move 2D-lemma to Tarski_Neutral_2D.thy
Move postulate-lemma to Tarski_postulate_Parallels.thy

(revision 90b76ef4bc10) <br>
"""

2025-04-19 = """
New Definitions (with arity left,right): Tarski_Neutral.thy
-----------------------------------------------------------
WARNING: Ar2p4(0,7): GeoCoq Ar2_4 O E E' A B C D :: IsaGeoCoq Ar2p4 PO E E' A B C D 

EqLTarski(1,1) EqA(1,1)
hypothesis_of_right_saccheri_quadrilaterals[HypothesisRightSaccheriQuadrilaterals](0,0)
hypothesis_of_acute_saccheri_quadrilaterals[HypothesisAcuteSaccheriQuadrilaterals](0,0)
hypothesis_of_obtuse_saccheri_quadrilaterals[HypothesisObtuseSaccheriQuadrilaterals](0,0)
Defect(0,6) Ar1(0,5) Ar2(0,6) Pj(2,2) Sum(0,6) Proj(2,4) Sump(0,6)
Prod(0,6) Prodp(0,6) Opp(0,5) Diff(0,6) sum3(0,7) Sum4(0,8) sum22(0,8) Ar2p4(0,7) 
Ps(0,3) Ng(0,3) LtP(0,5) LeP(0,5) Length(0,6) IsLength(0,6) Sumg(0,6) Prodg(0,6)
PythRel(0,6) SinEq(0,4) LtPs(0,5)

Porting Files (context Tarski_neutral_dimensionless)
-------------
  theories/Main/Meta_theory/Dimension_axioms/upper_dim_3.v
  theories/Main/Annexes/quadrilaterals.v
  theories/Main/Annexes/saccheri.v
  theories/Main/Annexes/defect.v
  theories/Main/Highschool/triangles.v

Add some postulate-definition to Tarski_postulate_Paralles.thy, (forgot 2025-04-18)

New Definitions (with arity left,right): Tarski_Neutral_Archimedes.thy
----------------------------------------------------------------------
WARNING: GeoCoq: Grad A B C :: IsaGeoCoq: Grad A B C <--> GradI A B C
         Grad 'GeoCoq' === GradI 'IsaGeoCoq'
	 
greenberg_s_axiom[GreenBergsAxiom](0,0)
aristotle_s_axiom[AristotleAxiom](0,0)
Axiom1(0,0) PreGrad(0,4) (fun)Sym(0,3) (fun)Gradn(0,3) Grad(0,3)
(inductive)GradI(0,3) Reach(0,4)
archimedes_axiom[ArchimedesAxiom](0,0)
(inductive)GradA(0,6) (inductive)GradAExp(0,6)
Grad2(0,6) (fun)SymR(0,2) (fun)GradExpn(0,3) GradExp(0,3)
GradExp2(0,6) (fun)MidR(0,2) (fun)GradExpInvn(0,3)
GradExpInv(0,3)

Porting Files (context Tarski_neutral_dimensionless)
-------------
  theories/Axioms/continuity_axioms.v
  theories/Main/Meta_theory/Continuity/grad.v
  theories/Main/Meta_theory/Continuity/archimedes.v
  theories/Main/Meta_theory/Continuity/angle_archimedes.v
  
(revision d8b69e02f8b3) <br>

"""

2025-04-21 = """
Tarski_Neutral_Archimedes.thy
--------------------------------
add section 'Equivalence Greenberg - Aristotle'
add lemma aristotle__greenberg
add lemma greenberg_aristotle
   (Note GeoCoq: This proof is inspired by
                 The elementary Archimedean axiom in absolute geometry, 
                 by Victor Pambuccian *) 
add theorem equiv_aristotle___greenberg

New Definitions (with arity left,right): Tarski_Neutral_Parallels.thy
---------------------------------------------------------------------

decidability_of_intersection[decidability_of_intersection](0,0)
alternate_interior_angles_postulate[AlternateInteriorAnglesPostulate](0,0)
consecutive_interior_angles_postulate[ConsecutiveInteriorAnglesPostulate](0,0)
alternative_playfair_s_postulate[AlternativePlayfairSPostulate](0,0)
proclus_postulate[ProclusPostulate](0,0) triangle_postulate[TrianglePostulate](0,0)
bachmann_s_lotschnittaxiom[BachmannsLotschnittaxiom](0,0)
legendre_s_parallel_postulate[LegendresParallelPostulate](0,0)
weak_inverse_projection_postulate[WeakInverseProjectionPostulate](0,0)
weak_triangle_circumscription_principle[WeakTriangleCircumscriptionPrinciple](0,0)
weak_tarski_s_parallel_postulate[WeakTarskiParallelPostulate](0,0)
existential_playfair_s_postulate[ExistentialPlayfairPostulate](0,0)
postulate_of_right_saccheri_quadrilaterals[PostulateRightSaccheriQuadrilaterals](0,0)
postulate_of_existence_of_a_right_saccheri_quadrilateral[PostulateExistenceRightSaccheriQuadrilateral](0,0)
postulate_of_existence_of_a_triangle_whose_angles_sum_to_two_rights[PostulateExistenceTriangleAnglesSumTwoRights](0,0)
inverse_projection_postulate[inverse_projection_postulate](0,0)
alternative_proclus_postulate[AlternativeProclusPostulate](0,0)
strong_parallel_postulate[StrongParallelPostulate](0,0)
triangle_circumscription_principle[TriangleCircumscriptionPrinciple](0,0)
thales_converse_postulate[ThalesConversePostulate](0,0)
existential_thales_postulate[ExistentialThalesPostulate](0,0)
thales_postulate[ThalesPostulate](0,0)
posidonius_postulate[PosidoniusPostulate](0,0)
postulate_of_right_lambert_quadrilaterals[PostulateOfRightLambertQuadrilaterals](0,0)
postulate_of_existence_of_a_right_lambert_quadrilateral[PostulateExistenceRightLambertQuadrilateral](0,0)
postulate_of_existence_of_similar_triangles[PostulateOfExistenceOfSimilarTriangles](0,0)
midpoint_converse_postulate[MidpointConversePostulate](0,0)
postulate_of_transitivity_of_parallelism[PostulateOfTransitivityOfParallelism](0,0)
perpendicular_transversal_postulate[PerpendicularTransversalPostulate](0,0)
postulate_of_parallelism_of_perpendicular_transversals[PostulateOfParallelismOfPerpendicularTransversals](0,0)
universal_posidonius_postulate[UniversalPosidoniusPostulate](0,0)
alternative_strong_parallel_postulate[AlternativeStrongParallelPostulate](0,0)

Redefinitions
=============
Postulate01:tarski_s_parallel_postulate
Postulate17:euclid_5
Postulate20:euclid_s_parallel_postulate
Postulate02:playfair_s_postulate
Postulate07:alternate_interior_angles_postulate
Postulate08:consecutive_interior_angles_postulate
Postulate12:alternative_playfair_s_postulate
Postulate13:proclus_postulate
Postulate03:triangle_postulate
Postulate04:bachmann_s_lotschnittaxiom
Postulate34:legendre_s_parallel_postulate
Postulate31:weak_inverse_projection_postulate
Postulate33:weak_triangle_circumscription_principle
Postulate32:weak_tarski_s_parallel_postulate
postulate35:existential_playfair_s_postulate
Postulate27:postulate_of_right_saccheri_quadrilaterals
Postulate28:postulate_of_existence_of_a_right_saccheri_quadrilateral
Postulate21:postulate_of_existence_of_a_triangle_whose_angles_sum_to_two_rights
Postulate16:inverse_projection_postulate
Postulate14:alternative_proclus_postulate
Postulate18:strong_parallel_postulate
Postulate15:triangle_circumscription_principle
Postulate25:thales_converse_postulate
Postulate26:existential_thales_postulate
Postulate24:thales_postulate
Postulate22:posidonius_postulate
Postulate29:postulate_of_right_lambert_quadrilaterals
Postulate30:postulate_of_existence_of_a_right_lambert_quadrilateral
Postulate23:postulate_of_existence_of_similar_triangles
Postulate06:midpoint_converse_postulate
Postulate05:postulate_of_transitivity_of_parallelism
Postulate09:perpendicular_transversal_postulate
Postulate10:postulate_of_parallelism_of_perpendicular_transversals
Postulate11:universal_posidonius_postulate
Postulate19:alternative_strong_parallel_postulate

Porting Files (context Tarski_neutral_dimensionless)
-------------
Main/Meta_theory/Parallel_postulates/tarski_s_euclid_remove_degenerated_cases.v
Main/Meta_theory/Parallel_postulates/alternate_interior_angles_consecutive_interior_angles.v
Main/Meta_theory/Parallel_postulates/alternate_interior_angles_playfair_bis.v
Main/Meta_theory/Parallel_postulates/alternate_interior_angles_proclus.v
Main/Meta_theory/Parallel_postulates/alternate_interior_angles_triangle.v
Main/Meta_theory/Parallel_postulates/bachmann_s_lotschnittaxiom_variant.v
Main/Meta_theory/Parallel_postulates/bachmann_s_lotschnittaxiom_legendre_s_parallel_postulate.v
Main/Meta_theory/Parallel_postulates/bachmann_s_lotschnittaxiom_weak_inverse_projection_postulate.v
Main/Meta_theory/Parallel_postulates/bachmann_s_lotschnittaxiom_weak_triangle_circumscription_principle.v
Main/Meta_theory/Parallel_postulates/consecutive_interior_angles_alternate_interior_angles.v
Main/Meta_theory/Parallel_postulates/existential_playfair_rah.v
Main/Meta_theory/Parallel_postulates/existential_saccheri_rah.v
Main/Meta_theory/Parallel_postulates/existential_triangle_rah.v
Main/Meta_theory/Parallel_postulates/inverse_projection_postulate_proclus_bis.v
Main/Meta_theory/Parallel_postulates/SPP_ID.v
Main/Meta_theory/Parallel_postulates/TCP_tarski.v
Main/Meta_theory/Parallel_postulates/thales_converse_postulate_thales_existence.v
Main/Meta_theory/Parallel_postulates/thales_converse_postulate_weak_triangle_circumscription_principle.v
Main/Meta_theory/Parallel_postulates/thales_existence_rah.v
Main/Meta_theory/Parallel_postulates/thales_postulate_thales_converse_postulate.v
Main/Meta_theory/Parallel_postulates/triangle_existential_triangle.v
Main/Meta_theory/Parallel_postulates/triangle_playfair_bis.v
Main/Meta_theory/Parallel_postulates/rah_existential_saccheri.v
Main/Meta_theory/Parallel_postulates/rah_posidonius_postulate.v
Main/Meta_theory/Parallel_postulates/rah_rectangle_principle.v
Main/Meta_theory/Parallel_postulates/rah_similar.v
Main/Meta_theory/Parallel_postulates/rah_thales_postulate.v
Main/Meta_theory/Parallel_postulates/rah_triangle.v
Main/Meta_theory/Parallel_postulates/rectangle_principle_rectangle_existence.v
Main/Meta_theory/Parallel_postulates/similar_rah.v
Main/Meta_theory/Parallel_postulates/SPP_tarski.v
Main/Meta_theory/Parallel_postulates/midpoint_playfair.v
Main/Meta_theory/Parallel_postulates/playfair_par_trans.v
Main/Meta_theory/Parallel_postulates/par_trans_playfair.v
Main/Meta_theory/Parallel_postulates/par_perp_perp_par_perp_2_par.v
Main/Meta_theory/Parallel_postulates/par_perp_2_par_par_perp_perp.v
Main/Meta_theory/Parallel_postulates/par_perp_perp_playfair.v
Main/Meta_theory/Parallel_postulates/playfair_universal_posidonius_postulate.v
Main/Meta_theory/Parallel_postulates/weak_inverse_projection_postulate_bachmann_s_lotschnittaxiom.v
Main/Meta_theory/Parallel_postulates/weak_triangle_circumscription_principle_bachmann_s_lotschnittaxiom.v
Main/Meta_theory/Parallel_postulates/universal_posidonius_postulate_par_perp_perp.v
Main/Meta_theory/Parallel_postulates/playfair_alternate_interior_angles.v
Main/Meta_theory/Parallel_postulates/playfair_bis_playfair.v
Main/Meta_theory/Parallel_postulates/playfair_midpoint.v
Main/Meta_theory/Parallel_postulates/par_perp_perp_TCP.v
Main/Meta_theory/Parallel_postulates/original_euclid_original_spp.v
Main/Meta_theory/Parallel_postulates/original_spp_inverse_projection_postulate.v
Main/Meta_theory/Parallel_postulates/proclus_bis_proclus.v
Main/Meta_theory/Parallel_postulates/proclus_SPP.v
Main/Meta_theory/Parallel_postulates/rectangle_existence_rah.v
Main/Meta_theory/Parallel_postulates/posidonius_postulate_rah.v
Main/Meta_theory/Parallel_postulates/playfair_existential_playfair.v
Main/Meta_theory/Parallel_postulates/proclus_aristotle.v
Main/Meta_theory/Continuity/aristotle.v
Main/Meta_theory/Parallel_postulates/parallel_postulates.v
Main/Meta_theory/Parallel_postulates/legendre.v
Main/Meta_theory/Parallel_postulates/szmielew.v

(revision 8bcb3f040eba) <br>

"""

2025-04-25 = """
Tarski_Neutral.thy: transform 'moura' tactic to other tactic

(revision a53e41f40732) <br>
"""
[extra]

[related]
