title = "MLSS Decision Procedure"
date = 2023-05-05
topics = [
  "Logic/General logic/Classical propositional logic",
  "Logic/Set theory",
  "Logic/General logic/Decidability of theories",
]
abstract = """
This formalization verifies a decision procedure due to Cantone and Zarba for a quantifier-free fragment of set theory.
The fragment is called multi-level syllogistic with singleton, or MLSS for short.
Its syntax syntax includes the usual set operations union, intersection, difference, membership, equality as well as the construction of a set containing a single element.
We specify the semantics of MLSS in terms of hereditarily finite sets and provide a sound and complete tableau calculus for it. 
We also provide an executable specification of a decision procedure that applies the rules of the calculus exhaustively and prove its termination.
Furthermore, we extend the calculus with a light-weight type system that paves the way for an integration of the procedure into Isabelle/HOL.
"""
license = "bsd"
note = ""

[authors]

[authors.stevens]
email = "stevens_email"

[contributors]

[notify]
stevens = "stevens_email"

[history]

[extra]

[related]
dois = [
  "10.1007/978-3-031-38499-8_28",
]
pubs = []
