title = "No-free-lunch theorem for machine learning"
date = 2025-08-23
topics = [
  "Computer science/Machine learning",
  "Mathematics/Probability theory",
]
abstract = "This entry is a formalization of the no-free-lunch theorem for machine learning following Section 5.1 of the book <a href=\"https://doi.org/10.1017/CBO9781107298019\">Understanding Machine Learning: From Theory to Algorithms</a> by Shai Shalev-Shwartz and Shai Ben-David. The theorem states that for binary classification prediction tasks, there is no universal learner, meaning that for every learning algorithms, there exists a distribution on which it fails."
license = "bsd"
note = ""

[authors]

[authors.hirata]
email = "hirata_email"

[contributors]

[notify]
hirata = "hirata_email"

[history]

[extra]

[related]
dois = []
pubs = []
