title = "Relational Divisibility"
date = 2025-10-09
topics = [
  "Mathematics/Order",
]
abstract = "We formalise key concepts and axioms of the divisibility relation on natural numbers using relation algebras. They use standard relational constructions for extrema, bounds, suprema, the univalent part and symmetric quotients, which we also formalise. We moreover prove that mono-atomic elements correspond to join-irreducible elements under the divisibility axioms."
license = "bsd"
note = ""

[authors]

[authors.guttmann]
homepage = "guttmann_homepage"

[contributors]

[notify]
guttmann = "guttmann_email"

[history]

[extra]

[related]
dois = []
pubs = []
